### PR TITLE
test CI compile failure

### PR DESCRIPTION
**Pull request by alex-courtis**

### CODE REVIEW

**Comment by alex-courtis** [comment]
@edrex compile fail messages OK

**Comment by alex-courtis** [comment]
@edrex test failures look great!

https://github.com/alex-courtis/way-displays/actions/runs/4836898512/jobs/8620384383?pr=95

Question: do we need the push action? On other projects we are just using pull_request...

**Comment by edrex** [comment]
> do we need the push action? On other projects we are just using pull_request

Seems like it comes down to maintainer preference. Merging a branch can combine changes that weren't previously tested together though, so running it on push, at least to the master branch, seems safest. 🤷

**Comment by alex-courtis** [comment]
> > do we need the push action? On other projects we are just using pull_request
> 
> Seems like it comes down to maintainer preference. Merging a branch can combine changes that weren't previously tested together though, so running it on push, at least to the master branch, seems safest. shrug

That works nicely. Once again many, many thanks for all your work @edrex

**Pull request closed without merging**
